build site:
  image: node:16-buster-slim
  stage: build
  only:
    - master
  environment: development
  script:
    - npm install --no-cache
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  image: alpine
  stage: deploy
  only:
    - master
  environment: development
  script:
    - apk add --no-cache rsync openssh
    - "command -v ssh-agent >/dev/null || ( apk add --update openssh )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 755 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $SSH_USER@$VM_IPADDRESS -p 64000 'chown -R intelli3:intelli3 public_html'
    - ssh $SSH_USER@$VM_IPADDRESS -p 64000 "source /home/intelli3/nodevenv/public_html/intelligo-landing-page/12/bin/activate && cd /home/intelli3/public_html/intelligo-landing-page/ && node -v && git checkout master && git pull origin master && npm ci && npm run build && cd dist && cp -r * ../../ && cd ../../ && chmod 755 dashboard.intelligo.id && cd api.intelligo.id && chmod 755 public/ && cd ../../ && chmod 755 public_html"
